# Generated by Django 6.1.1 on 2026-09-07 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='habit',
        ),
        migrations.RemoveField(
            model_name='running',
            name='habit',
        ),
        migrations.AlterField(
            model_name='habit',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('mood', models.IntegerField()),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='habits.habit')),
            ],
        ),
        migrations.DeleteModel(
            name='Gym',
        ),
        migrations.DeleteModel(
            name='Reading',
        ),
        migrations.DeleteModel(
            name='Running',
        ),
    ]
